### ISSUE TITLE
Running on macos

### ISSUE THREAD

**Issue by asselinpaul** [thesephist/lucerne#4]
Hi,
Trying to get this running locally.
I'm able to run the server (after having set my credentials):
<img width="1438" alt="Screen Shot 2021-02-23 at 2 04 27 PM" src="https://user-images.githubusercontent.com/868249/108894353-2ba09380-75e0-11eb-8009-90594964f4a9.png">

But I get stuck with this loading behavior:
<img width="1226" alt="Screen Shot 2021-02-23 at 2 04 38 PM" src="https://user-images.githubusercontent.com/868249/108894354-2c392a00-75e0-11eb-9eda-83630415dc9b.png">

Console:
<img width="1226" alt="Screen Shot 2021-02-23 at 2 06 33 PM" src="https://user-images.githubusercontent.com/868249/108894499-5d195f00-75e0-11eb-8128-10d39d462778.png">

Wondering if anyone else has encountered this.

**Comment by thesephist** [comment]
Hey @asselinpaul, it looks like Twitter might be returning something that Lucerne didn't expect. I'm suspecting some kind of an authentication issue given that all 3 API calls are failing, but can't say for certain. Could you check what responses you get in the **Network** tab of the devtools? Specifically in response to the API endpoints that are erroring out.

Feel free to email me if you'd rather not put personal data on GitHub issues -- linus at thesephist dot com

**Comment by asselinpaul** [comment]
@thesephist was using a wrong ConsumerKey. thank you!
For future ref, "Terminology clarification" is useful here: https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

**Comment by thesephist** [comment]
Oh yeah, I remember getting confused myself too. They use different words for it in different places. Glad you got it figured out!
